#:property TargetFramework=net10.0
// Generates src/IZLang/Binding/GameEnums.g.cs from the game's Assembly-CSharp.dll.
//
// Run it after every Stationeers update that touches the logic enums:
//   dotnet run tools/GenLogicTypes/gen.cs [path-to-Assembly-CSharp.dll] [output.cs]
//
// The point is that IZLang NEVER references Assembly-CSharp: the table lands as
// source code, so the compiler and the VM stay testable outside the game.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

string dll = args.Length > 0
    ? args[0]
    : @"C:\Program Files (x86)\Steam\steamapps\common\Stationeers\rocketstation_Data\Managed\Assembly-CSharp.dll";

string outPath = args.Length > 1
    ? args[1]
    : Path.Combine("src", "IZLang", "Binding", "GameEnums.g.cs");

if (!File.Exists(dll))
{
    Console.Error.WriteLine($"could not find Assembly-CSharp.dll at: {dll}");
    return 1;
}

using var fs = File.OpenRead(dll);
using var pe = new PEReader(fs);
var md = pe.GetMetadataReader();

var logicTypes = ReadEnum("Assets.Scripts.Objects.Motherboards.LogicType");
var slotTypes = ReadEnum("Assets.Scripts.Objects.Motherboards.LogicSlotType");

if (logicTypes.Count == 0 || slotTypes.Count == 0)
{
    Console.Error.WriteLine("could not read the enums; did the game change its namespaces?");
    return 1;
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//   Generated by tools/GenLogicTypes/gen.cs from the game's Assembly-CSharp.dll.");
sb.AppendLine("//   Do not edit by hand: run the generator again.");
sb.AppendLine($"//   LogicType: {logicTypes.Count} entries | LogicSlotType: {slotTypes.Count} entries");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine("namespace IZLang.Binding");
sb.AppendLine("{");
sb.AppendLine("    /// <summary>Mirror of the game's logic enums, as data.</summary>");
sb.AppendLine("    public static partial class GameEnums");
sb.AppendLine("    {");

EmitTable(sb, "LogicTypeByName", logicTypes);
sb.AppendLine();
EmitTable(sb, "LogicSlotTypeByName", slotTypes);

sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"wrote {outPath}: {logicTypes.Count} LogicType, {slotTypes.Count} LogicSlotType");
return 0;

void EmitTable(StringBuilder sb, string name, List<(string Name, int Value)> entries)
{
    sb.AppendLine($"        private static readonly Dictionary<string, int> _{name} =");
    sb.AppendLine($"            new Dictionary<string, int>({entries.Count}, StringComparer.Ordinal)");
    sb.AppendLine("            {");
    foreach (var (n, v) in entries)
        sb.AppendLine($"                [\"{n}\"] = {v},");
    sb.AppendLine("            };");
    sb.AppendLine();
    sb.AppendLine($"        public static IReadOnlyDictionary<string, int> {name} => _{name};");
}

List<(string Name, int Value)> ReadEnum(string fullName)
{
    var result = new List<(string, int)>();
    foreach (var h in md.TypeDefinitions)
    {
        var td = md.GetTypeDefinition(h);
        var ns = md.GetString(td.Namespace);
        var nm = md.GetString(td.Name);
        var full = string.IsNullOrEmpty(ns) ? nm : ns + "." + nm;
        if (!full.Equals(fullName, StringComparison.Ordinal)) continue;

        foreach (var fh in td.GetFields())
        {
            var f = md.GetFieldDefinition(fh);
            if (!f.Attributes.HasFlag(FieldAttributes.Literal)) continue;

            var ch = f.GetDefaultValue();
            if (ch.IsNil) continue;

            var con = md.GetConstant(ch);
            var blob = md.GetBlobReader(con.Value);
            int value = con.TypeCode switch
            {
                ConstantTypeCode.Int32 => blob.ReadInt32(),
                ConstantTypeCode.UInt32 => (int)blob.ReadUInt32(),
                ConstantTypeCode.Int16 => blob.ReadInt16(),
                ConstantTypeCode.UInt16 => blob.ReadUInt16(),
                ConstantTypeCode.Byte => blob.ReadByte(),
                ConstantTypeCode.SByte => blob.ReadSByte(),
                _ => int.MinValue,
            };
            if (value == int.MinValue) continue;

            result.Add((md.GetString(f.Name), value));
        }
    }
    return result;
}
