#:property TargetFramework=net10.0
// Generates src/IZLang/Binding/GameEnums.g.cs from the game's Assembly-CSharp.dll.
//
// Run it after every Stationeers update that touches the logic enums:
//   dotnet run tools/GenLogicTypes/gen.cs [path-to-Assembly-CSharp.dll] [output.cs]
//
// The point is that IZLang NEVER references Assembly-CSharp: the table lands as
// source code, so the compiler and the VM stay testable outside the game.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

// The named constant groups the game's IC10 exposes, in the order its
// ProgrammableChip static constructor registers them (the InternalEnums field).
// The left side is the name a script writes before the dot; the right side is
// the enum inside Assembly-CSharp it mirrors.
//
// Where IC10 registers a group under an empty name - its values are written bare
// there - we use the game's own type name instead, so every value in IZ is
// reached the same way: Group.Value.
var groups = new (string Name, string Type)[]
{
    ("LogicType",          "Assets.Scripts.Objects.Motherboards.LogicType"),
    ("LogicSlotType",      "Assets.Scripts.Objects.Motherboards.LogicSlotType"),
    ("LogicReagentMode",   "Assets.Scripts.Objects.Electrical.LogicReagentMode"),
    ("LogicBatchMethod",   "Assets.Scripts.Objects.Electrical.LogicBatchMethod"),
    ("Sound",              "Assets.Scripts.Objects.Electrical.SoundAlert"),
    ("TransmitterMode",    "Assets.Scripts.Objects.Electrical.LogicTransmitterMode"),
    ("ElevatorMode",       "Assets.Scripts.ElevatorMode"),
    ("Color",              "Assets.Scripts.Objects.Motherboards.ColorType"),
    ("EntityState",        "Assets.Scripts.Objects.Entities.EntityState"),
    ("AirControl",         "Assets.Scripts.Objects.Motherboards.AirControlMode"),
    ("DaylightSensorMode", "Assets.Scripts.Objects.Electrical.DaylightSensor+DaylightSensorMode"),
    ("ConditionOperation", "Assets.Scripts.Objects.Motherboards.ConditionOperation"),
    ("AirCon",             "Assets.Scripts.Objects.AirConditioningMode"),
    ("Vent",               "Assets.Scripts.Objects.Pipes.VentDirection"),
    ("FiltrationMode",     "Assets.Scripts.Objects.Pipes.FiltrationMode"),
    ("PowerMode",          "Assets.Scripts.Objects.Electrical.PowerMode"),
    ("RobotMode",          "Assets.Scripts.Objects.RobotMode"),
    ("SortingClass",       "Assets.Scripts.Objects.SortingClass"),
    ("SlotClass",          "Assets.Scripts.Objects.Slot+Class"),
    ("GasType",            "Assets.Scripts.Atmospherics.Chemistry+GasType"),
    ("RocketMode",         "Objects.Rockets.RocketMode"),
    ("ReEntryProfile",     "Objects.Rockets.ReEntryProfile"),
    ("SorterInstruction",  "Assets.Scripts.Objects.Electrical.SorterInstruction"),
    ("PrinterInstruction", "Assets.Scripts.Objects.Electrical.PrinterInstruction"),
    ("TraderInstruction",  "Assets.Scripts.Objects.Electrical.TraderInstruction"),
    ("ShuttleType",        "Assets.Scripts.ShuttleType"),
    ("HashType",           "Assets.Scripts.Objects.Motherboards.HashType"),
    ("DisplayMode",        "Assets.Scripts.Objects.Electrical.LogicDisplay+DisplayMode"),
    ("SettingDisplayMode", "Assets.Scripts.Objects.Electrical.SettingDisplayMode"),
    ("NodeType",           "Objects.Rockets.NodeType"),
};

string dll = args.Length > 0
    ? args[0]
    : @"C:\Program Files (x86)\Steam\steamapps\common\Stationeers\rocketstation_Data\Managed\Assembly-CSharp.dll";

string outPath = args.Length > 1
    ? args[1]
    : Path.Combine("src", "IZLang", "Binding", "GameEnums.g.cs");

if (!File.Exists(dll))
{
    Console.Error.WriteLine($"could not find Assembly-CSharp.dll at: {dll}");
    return 1;
}

using var fs = File.OpenRead(dll);
using var pe = new PEReader(fs);
var md = pe.GetMetadataReader();

var tables = new List<(string Name, List<(string Name, int Value)> Entries)>();
foreach (var (name, type) in groups)
{
    var entries = ReadEnum(type);
    if (entries.Count == 0)
    {
        Console.Error.WriteLine($"could not read '{type}'; did the game change its namespaces?");
        return 1;
    }
    tables.Add((name, entries));
}

int total = 0;
foreach (var table in tables) total += table.Entries.Count;

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//   Generated by tools/GenLogicTypes/gen.cs from the game's Assembly-CSharp.dll.");
sb.AppendLine("//   Do not edit by hand: run the generator again.");
sb.AppendLine($"//   {tables.Count} constant groups | {total} values");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine("namespace IZLang.Binding");
sb.AppendLine("{");
sb.AppendLine("    /// <summary>Mirror of the game's logic enums, as data.</summary>");
sb.AppendLine("    public static partial class GameEnums");
sb.AppendLine("    {");

foreach (var (name, entries) in tables)
{
    EmitTable(sb, TableName(name), entries);
    sb.AppendLine();
}

// The registry the compiler and the editor walk: group name -> its values.
sb.AppendLine("        private static readonly Dictionary<string, IReadOnlyDictionary<string, int>> _ConstantGroups =");
sb.AppendLine($"            new Dictionary<string, IReadOnlyDictionary<string, int>>({tables.Count}, StringComparer.Ordinal)");
sb.AppendLine("            {");
foreach (var (name, _) in tables)
    sb.AppendLine($"                [\"{name}\"] = _{TableName(name)},");
sb.AppendLine("            };");
sb.AppendLine();
sb.AppendLine("        /// <summary>Every named constant group the game exposes: Color, AirCon, GasType...</summary>");
sb.AppendLine("        public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> ConstantGroups => _ConstantGroups;");

sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"wrote {outPath}: {tables.Count} groups, {total} values");
foreach (var (name, entries) in tables) Console.WriteLine($"  {name}: {entries.Count}");
return 0;

// LogicType and LogicSlotType keep their historical '...ByName' property so the
// code that already reads them does not have to change.
static string TableName(string group) =>
    group == "LogicType" || group == "LogicSlotType" ? group + "ByName" : group;

void EmitTable(StringBuilder sb, string name, List<(string Name, int Value)> entries)
{
    sb.AppendLine($"        private static readonly Dictionary<string, int> _{name} =");
    sb.AppendLine($"            new Dictionary<string, int>({entries.Count}, StringComparer.Ordinal)");
    sb.AppendLine("            {");
    foreach (var (n, v) in entries)
        sb.AppendLine($"                [\"{n}\"] = {v},");
    sb.AppendLine("            };");
    sb.AppendLine();
    sb.AppendLine($"        public static IReadOnlyDictionary<string, int> {name} => _{name};");
}

List<(string Name, int Value)> ReadEnum(string fullName)
{
    var result = new List<(string, int)>();
    var seen = new HashSet<string>(StringComparer.Ordinal);

    foreach (var h in md.TypeDefinitions)
    {
        var td = md.GetTypeDefinition(h);

        if (!IsEnum(td)) continue;
        if (!FullNameOf(h).Equals(fullName, StringComparison.Ordinal)) continue;

        foreach (var fh in td.GetFields())
        {
            var f = md.GetFieldDefinition(fh);
            if (!f.Attributes.HasFlag(FieldAttributes.Literal)) continue;

            var ch = f.GetDefaultValue();
            if (ch.IsNil) continue;

            var con = md.GetConstant(ch);
            var blob = md.GetBlobReader(con.Value);
            long value = con.TypeCode switch
            {
                ConstantTypeCode.Int32 => blob.ReadInt32(),
                ConstantTypeCode.UInt32 => blob.ReadUInt32(),
                ConstantTypeCode.Int16 => blob.ReadInt16(),
                ConstantTypeCode.UInt16 => blob.ReadUInt16(),
                ConstantTypeCode.Byte => blob.ReadByte(),
                ConstantTypeCode.SByte => blob.ReadSByte(),
                ConstantTypeCode.Int64 => blob.ReadInt64(),
                ConstantTypeCode.UInt64 => (long)blob.ReadUInt64(),
                _ => long.MinValue,
            };
            if (value == long.MinValue || value > int.MaxValue || value < int.MinValue) continue;

            // Some enums declare an alias next to the value it repeats; the first
            // spelling is the canonical one.
            string fieldName = md.GetString(f.Name);
            if (seen.Add(fieldName)) result.Add((fieldName, (int)value));
        }
    }
    return result;
}

// A nested type reports an empty namespace, so it needs its declaring type in
// front of it: 'Assets.Scripts.Atmospherics.Chemistry+GasType' is not the same
// enum as 'Assets.Scripts.Networking.NetworkUpdateType+GasType'.
string FullNameOf(TypeDefinitionHandle handle)
{
    var td = md.GetTypeDefinition(handle);
    var name = md.GetString(td.Name);

    var declaring = td.GetDeclaringType();
    if (!declaring.IsNil) return FullNameOf(declaring) + "+" + name;

    var ns = md.GetString(td.Namespace);
    return ns.Length == 0 ? name : ns + "." + name;
}

bool IsEnum(TypeDefinition td)
{
    var baseType = td.BaseType;
    if (baseType.IsNil || baseType.Kind != HandleKind.TypeReference) return false;

    var reference = md.GetTypeReference((TypeReferenceHandle)baseType);
    return md.GetString(reference.Namespace) == "System" && md.GetString(reference.Name) == "Enum";
}
