using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace IZLang.Devices
{
    /// <summary>
    /// Catalog serialization in a TAB separated line format.
    ///
    /// Deliberately not JSON: the catalog has thousands of lines, it has to load fast
    /// during game startup, and a one-entity-per-line format is readable in a diff
    /// when Stationeers updates. It also avoids dragging a JSON parser into IZLang.
    ///
    ///   V  1                                   format version
    ///   G  0.2.5678.22role                     game version
    ///   D  PrefabName  hash  slots  Name       start of a device
    ///   P  Name  logicType  rw                 property (rw | r | w)
    ///   S  Name  logicSlotType                 slot property
    ///
    /// Blank lines and lines starting with '#' are ignored.
    /// </summary>
    public static class CatalogFormat
    {
        public const int CurrentVersion = 1;

        private const char Separator = '\t';

        // ==================================================================
        //  Writing
        // ==================================================================

        public static string Write(DeviceCatalog catalog)
        {
            var sb = new StringBuilder();

            sb.Append("# IZCode device catalog - generated by the game, do not edit by hand.\n");
            sb.Append("# Regenerate it by deleting this file and opening the game again.\n");
            sb.Append("V").Append(Separator).Append(CurrentVersion).Append('\n');
            sb.Append("G").Append(Separator).Append(catalog.GameVersion).Append('\n');

            foreach (var device in catalog.Devices)
            {
                sb.Append("D").Append(Separator)
                  .Append(device.PrefabName).Append(Separator)
                  .Append(device.PrefabHash.ToString(CultureInfo.InvariantCulture)).Append(Separator)
                  .Append(device.SlotCount.ToString(CultureInfo.InvariantCulture)).Append(Separator)
                  .Append(Sanitize(device.DisplayName)).Append('\n');

                foreach (var property in device.Properties)
                {
                    sb.Append("P").Append(Separator)
                      .Append(property.Name).Append(Separator)
                      .Append(property.LogicType.ToString(CultureInfo.InvariantCulture)).Append(Separator)
                      .Append(property.Access.Label()).Append('\n');
                }

                foreach (var slot in device.SlotProperties)
                {
                    sb.Append("S").Append(Separator)
                      .Append(slot.Name).Append(Separator)
                      .Append(slot.LogicSlotType.ToString(CultureInfo.InvariantCulture)).Append('\n');
                }
            }

            return sb.ToString();
        }

        /// <summary>The display name may carry TABs or line breaks coming from localization.</summary>
        private static string Sanitize(string text)
        {
            if (string.IsNullOrEmpty(text)) return string.Empty;
            return text.Replace('\t', ' ').Replace('\r', ' ').Replace('\n', ' ');
        }

        // ==================================================================
        //  Reading
        // ==================================================================

        /// <summary>
        /// Reads a catalog. Never throws: a malformed line is skipped, because a
        /// partial catalog beats dead completion - and the file may have been truncated
        /// by a crash in the middle of a write.
        /// </summary>
        public static DeviceCatalog Read(string text)
        {
            if (string.IsNullOrEmpty(text)) return DeviceCatalog.Empty;

            var devices = new List<DeviceInfo>();
            string gameVersion = string.Empty;

            // Device under construction: the P/S lines that follow belong to it.
            string? currentName = null;
            int currentHash = 0;
            int currentSlots = 0;
            string currentDisplay = string.Empty;
            var properties = new List<LogicProperty>();
            var slotProperties = new List<SlotProperty>();

            void FlushDevice()
            {
                if (currentName == null) return;
                devices.Add(new DeviceInfo(currentName, currentHash, currentDisplay, currentSlots,
                    properties.ToArray(), slotProperties.ToArray()));
                properties.Clear();
                slotProperties.Clear();
                currentName = null;
            }

            foreach (var rawLine in text.Split('\n'))
            {
                string line = rawLine.TrimEnd('\r');
                if (line.Length == 0 || line[0] == '#') continue;

                var parts = line.Split(Separator);
                switch (parts[0])
                {
                    case "V":
                        // Different format version: we do not try to guess, the caller
                        // regenerates the catalog.
                        if (parts.Length < 2 || !TryParseInt(parts[1], out int version) ||
                            version != CurrentVersion)
                            return DeviceCatalog.Empty;
                        break;

                    case "G":
                        gameVersion = parts.Length > 1 ? parts[1] : string.Empty;
                        break;

                    case "D":
                    {
                        FlushDevice();
                        if (parts.Length < 4) break;
                        if (!TryParseInt(parts[2], out int hash)) break;
                        if (!TryParseInt(parts[3], out int slots)) slots = 0;

                        currentName = parts[1];
                        currentHash = hash;
                        currentSlots = slots;
                        currentDisplay = parts.Length > 4 ? parts[4] : parts[1];
                        break;
                    }

                    case "P":
                    {
                        if (currentName == null || parts.Length < 4) break;
                        if (!TryParseInt(parts[2], out int logicType)) break;
                        properties.Add(new LogicProperty(parts[1], logicType, ParseAccess(parts[3])));
                        break;
                    }

                    case "S":
                    {
                        if (currentName == null || parts.Length < 3) break;
                        if (!TryParseInt(parts[2], out int slotType)) break;
                        slotProperties.Add(new SlotProperty(parts[1], slotType));
                        break;
                    }
                }
            }

            FlushDevice();
            return new DeviceCatalog(devices, gameVersion);
        }

        private static bool TryParseInt(string text, out int value) =>
            int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);

        private static LogicAccess ParseAccess(string text)
        {
            switch (text)
            {
                case "rw": return LogicAccess.ReadWrite;
                case "r": return LogicAccess.Read;
                case "w": return LogicAccess.Write;
                default: return LogicAccess.None;
            }
        }

        // ==================================================================
        //  JSON export
        // ==================================================================

        /// <summary>
        /// The same information in JSON, for use outside the mod (wiki, external tool,
        /// text editor). Write only: the mod reads the line format.
        /// </summary>
        public static string WriteJson(DeviceCatalog catalog)
        {
            var sb = new StringBuilder();
            sb.Append("{\n");
            sb.Append("  \"formatVersion\": ").Append(CurrentVersion).Append(",\n");
            sb.Append("  \"gameVersion\": ").Append(Quote(catalog.GameVersion)).Append(",\n");
            sb.Append("  \"deviceCount\": ").Append(catalog.Devices.Count).Append(",\n");
            sb.Append("  \"devices\": [\n");

            for (int i = 0; i < catalog.Devices.Count; i++)
            {
                var device = catalog.Devices[i];
                sb.Append("    {\n");
                sb.Append("      \"prefabName\": ").Append(Quote(device.PrefabName)).Append(",\n");
                sb.Append("      \"prefabHash\": ").Append(device.PrefabHash).Append(",\n");
                sb.Append("      \"displayName\": ").Append(Quote(device.DisplayName)).Append(",\n");
                sb.Append("      \"slotCount\": ").Append(device.SlotCount).Append(",\n");

                sb.Append("      \"properties\": [");
                for (int p = 0; p < device.Properties.Count; p++)
                {
                    var property = device.Properties[p];
                    if (p > 0) sb.Append(',');
                    sb.Append("\n        {\"name\": ").Append(Quote(property.Name))
                      .Append(", \"logicType\": ").Append(property.LogicType)
                      .Append(", \"read\": ").Append(property.Access.CanRead() ? "true" : "false")
                      .Append(", \"write\": ").Append(property.Access.CanWrite() ? "true" : "false")
                      .Append('}');
                }
                sb.Append(device.Properties.Count > 0 ? "\n      ],\n" : "],\n");

                sb.Append("      \"slotProperties\": [");
                for (int s = 0; s < device.SlotProperties.Count; s++)
                {
                    var slot = device.SlotProperties[s];
                    if (s > 0) sb.Append(',');
                    sb.Append("\n        {\"name\": ").Append(Quote(slot.Name))
                      .Append(", \"logicSlotType\": ").Append(slot.LogicSlotType)
                      .Append('}');
                }
                sb.Append(device.SlotProperties.Count > 0 ? "\n      ]\n" : "]\n");

                sb.Append(i + 1 < catalog.Devices.Count ? "    },\n" : "    }\n");
            }

            sb.Append("  ]\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        private static string Quote(string? text)
        {
            if (string.IsNullOrEmpty(text)) return "\"\"";

            var sb = new StringBuilder(text!.Length + 2);
            sb.Append('"');
            foreach (char c in text)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < 0x20) sb.Append("\\u").Append(((int)c).ToString("x4"));
                        else sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
