// <auto-generated>
//   Generated by tools/GenLogicTypes/gen.cs from the game's Assembly-CSharp.dll.
//   Do not edit by hand: run the generator again.
//   30 constant groups | 669 values
// </auto-generated>

using System;
using System.Collections.Generic;

namespace IZLang.Binding
{
    /// <summary>Mirror of the game's logic enums, as data.</summary>
    public static partial class GameEnums
    {
        private static readonly Dictionary<string, int> _LogicTypeByName =
            new Dictionary<string, int>(358, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Power"] = 1,
                ["Open"] = 2,
                ["Mode"] = 3,
                ["Error"] = 4,
                ["Pressure"] = 5,
                ["Temperature"] = 6,
                ["PressureExternal"] = 7,
                ["PressureInternal"] = 8,
                ["Activate"] = 9,
                ["Lock"] = 10,
                ["Charge"] = 11,
                ["Setting"] = 12,
                ["Reagents"] = 13,
                ["RatioOxygen"] = 14,
                ["RatioCarbonDioxide"] = 15,
                ["RatioNitrogen"] = 16,
                ["RatioPollutant"] = 17,
                ["RatioMethane"] = 18,
                ["RatioWater"] = 19,
                ["Horizontal"] = 20,
                ["Vertical"] = 21,
                ["SolarAngle"] = 22,
                ["Maximum"] = 23,
                ["Ratio"] = 24,
                ["PowerPotential"] = 25,
                ["PowerActual"] = 26,
                ["Quantity"] = 27,
                ["On"] = 28,
                ["ImportQuantity"] = 29,
                ["ImportSlotOccupant"] = 30,
                ["ExportQuantity"] = 31,
                ["ExportSlotOccupant"] = 32,
                ["RequiredPower"] = 33,
                ["HorizontalRatio"] = 34,
                ["VerticalRatio"] = 35,
                ["PowerRequired"] = 36,
                ["Idle"] = 37,
                ["Color"] = 38,
                ["ElevatorSpeed"] = 39,
                ["ElevatorLevel"] = 40,
                ["RecipeHash"] = 41,
                ["ExportSlotHash"] = 42,
                ["ImportSlotHash"] = 43,
                ["PlantHealth1"] = 44,
                ["PlantHealth2"] = 45,
                ["PlantHealth3"] = 46,
                ["PlantHealth4"] = 47,
                ["PlantGrowth1"] = 48,
                ["PlantGrowth2"] = 49,
                ["PlantGrowth3"] = 50,
                ["PlantGrowth4"] = 51,
                ["PlantEfficiency1"] = 52,
                ["PlantEfficiency2"] = 53,
                ["PlantEfficiency3"] = 54,
                ["PlantEfficiency4"] = 55,
                ["PlantHash1"] = 56,
                ["PlantHash2"] = 57,
                ["PlantHash3"] = 58,
                ["PlantHash4"] = 59,
                ["RequestHash"] = 60,
                ["CompletionRatio"] = 61,
                ["ClearMemory"] = 62,
                ["ExportCount"] = 63,
                ["ImportCount"] = 64,
                ["PowerGeneration"] = 65,
                ["TotalMoles"] = 66,
                ["Volume"] = 67,
                ["Plant"] = 68,
                ["Harvest"] = 69,
                ["Output"] = 70,
                ["PressureSetting"] = 71,
                ["TemperatureSetting"] = 72,
                ["TemperatureExternal"] = 73,
                ["Filtration"] = 74,
                ["AirRelease"] = 75,
                ["PositionX"] = 76,
                ["PositionY"] = 77,
                ["PositionZ"] = 78,
                ["VelocityMagnitude"] = 79,
                ["VelocityRelativeX"] = 80,
                ["VelocityRelativeY"] = 81,
                ["VelocityRelativeZ"] = 82,
                ["RatioNitrousOxide"] = 83,
                ["PrefabHash"] = 84,
                ["ForceWrite"] = 85,
                ["SignalStrength"] = 86,
                ["SignalID"] = 87,
                ["TargetX"] = 88,
                ["TargetY"] = 89,
                ["TargetZ"] = 90,
                ["SettingInput"] = 91,
                ["SettingOutput"] = 92,
                ["CurrentResearchPodType"] = 93,
                ["ManualResearchRequiredPod"] = 94,
                ["MineablesInVicinity"] = 95,
                ["MineablesInQueue"] = 96,
                ["NextWeatherEventTime"] = 97,
                ["Combustion"] = 98,
                ["Fuel"] = 99,
                ["ReturnFuelCost"] = 100,
                ["CollectableGoods"] = 101,
                ["Time"] = 102,
                ["Bpm"] = 103,
                ["EnvironmentEfficiency"] = 104,
                ["WorkingGasEfficiency"] = 105,
                ["PressureInput"] = 106,
                ["TemperatureInput"] = 107,
                ["RatioOxygenInput"] = 108,
                ["RatioCarbonDioxideInput"] = 109,
                ["RatioNitrogenInput"] = 110,
                ["RatioPollutantInput"] = 111,
                ["RatioMethaneInput"] = 112,
                ["RatioWaterInput"] = 113,
                ["RatioNitrousOxideInput"] = 114,
                ["TotalMolesInput"] = 115,
                ["PressureInput2"] = 116,
                ["TemperatureInput2"] = 117,
                ["RatioOxygenInput2"] = 118,
                ["RatioCarbonDioxideInput2"] = 119,
                ["RatioNitrogenInput2"] = 120,
                ["RatioPollutantInput2"] = 121,
                ["RatioMethaneInput2"] = 122,
                ["RatioWaterInput2"] = 123,
                ["RatioNitrousOxideInput2"] = 124,
                ["TotalMolesInput2"] = 125,
                ["PressureOutput"] = 126,
                ["TemperatureOutput"] = 127,
                ["RatioOxygenOutput"] = 128,
                ["RatioCarbonDioxideOutput"] = 129,
                ["RatioNitrogenOutput"] = 130,
                ["RatioPollutantOutput"] = 131,
                ["RatioMethaneOutput"] = 132,
                ["RatioWaterOutput"] = 133,
                ["RatioNitrousOxideOutput"] = 134,
                ["TotalMolesOutput"] = 135,
                ["PressureOutput2"] = 136,
                ["TemperatureOutput2"] = 137,
                ["RatioOxygenOutput2"] = 138,
                ["RatioCarbonDioxideOutput2"] = 139,
                ["RatioNitrogenOutput2"] = 140,
                ["RatioPollutantOutput2"] = 141,
                ["RatioMethaneOutput2"] = 142,
                ["RatioWaterOutput2"] = 143,
                ["RatioNitrousOxideOutput2"] = 144,
                ["TotalMolesOutput2"] = 145,
                ["CombustionInput"] = 146,
                ["CombustionInput2"] = 147,
                ["CombustionOutput"] = 148,
                ["CombustionOutput2"] = 149,
                ["OperationalTemperatureEfficiency"] = 150,
                ["TemperatureDifferentialEfficiency"] = 151,
                ["PressureEfficiency"] = 152,
                ["CombustionLimiter"] = 153,
                ["Throttle"] = 154,
                ["Rpm"] = 155,
                ["Stress"] = 156,
                ["InterrogationProgress"] = 157,
                ["TargetPadIndex"] = 158,
                ["SizeX"] = 160,
                ["SizeY"] = 161,
                ["SizeZ"] = 162,
                ["MinimumWattsToContact"] = 163,
                ["WattsReachingContact"] = 164,
                ["Channel0"] = 165,
                ["Channel1"] = 166,
                ["Channel2"] = 167,
                ["Channel3"] = 168,
                ["Channel4"] = 169,
                ["Channel5"] = 170,
                ["Channel6"] = 171,
                ["Channel7"] = 172,
                ["LineNumber"] = 173,
                ["Flush"] = 174,
                ["SoundAlert"] = 175,
                ["SolarIrradiance"] = 176,
                ["RatioLiquidNitrogen"] = 177,
                ["RatioLiquidNitrogenInput"] = 178,
                ["RatioLiquidNitrogenInput2"] = 179,
                ["RatioLiquidNitrogenOutput"] = 180,
                ["RatioLiquidNitrogenOutput2"] = 181,
                ["VolumeOfLiquid"] = 182,
                ["RatioLiquidOxygen"] = 183,
                ["RatioLiquidOxygenInput"] = 184,
                ["RatioLiquidOxygenInput2"] = 185,
                ["RatioLiquidOxygenOutput"] = 186,
                ["RatioLiquidOxygenOutput2"] = 187,
                ["RatioLiquidMethane"] = 188,
                ["RatioLiquidMethaneInput"] = 189,
                ["RatioLiquidMethaneInput2"] = 190,
                ["RatioLiquidMethaneOutput"] = 191,
                ["RatioLiquidMethaneOutput2"] = 192,
                ["RatioSteam"] = 193,
                ["RatioSteamInput"] = 194,
                ["RatioSteamInput2"] = 195,
                ["RatioSteamOutput"] = 196,
                ["RatioSteamOutput2"] = 197,
                ["ContactTypeId"] = 198,
                ["RatioLiquidCarbonDioxide"] = 199,
                ["RatioLiquidCarbonDioxideInput"] = 200,
                ["RatioLiquidCarbonDioxideInput2"] = 201,
                ["RatioLiquidCarbonDioxideOutput"] = 202,
                ["RatioLiquidCarbonDioxideOutput2"] = 203,
                ["RatioLiquidPollutant"] = 204,
                ["RatioLiquidPollutantInput"] = 205,
                ["RatioLiquidPollutantInput2"] = 206,
                ["RatioLiquidPollutantOutput"] = 207,
                ["RatioLiquidPollutantOutput2"] = 208,
                ["RatioLiquidNitrousOxide"] = 209,
                ["RatioLiquidNitrousOxideInput"] = 210,
                ["RatioLiquidNitrousOxideInput2"] = 211,
                ["RatioLiquidNitrousOxideOutput"] = 212,
                ["RatioLiquidNitrousOxideOutput2"] = 213,
                ["Progress"] = 214,
                ["DestinationCode"] = 215,
                ["Acceleration"] = 216,
                ["ReferenceId"] = 217,
                ["AutoShutOff"] = 218,
                ["Mass"] = 219,
                ["DryMass"] = 220,
                ["Thrust"] = 221,
                ["Weight"] = 222,
                ["ThrustToWeight"] = 223,
                ["TimeToDestination"] = 224,
                ["BurnTimeRemaining"] = 225,
                ["AutoLand"] = 226,
                ["ForwardX"] = 227,
                ["ForwardY"] = 228,
                ["ForwardZ"] = 229,
                ["Orientation"] = 230,
                ["VelocityX"] = 231,
                ["VelocityY"] = 232,
                ["VelocityZ"] = 233,
                ["PassedMoles"] = 234,
                ["ExhaustVelocity"] = 235,
                ["FlightControlRule"] = 236,
                ["ReEntryAltitude"] = 237,
                ["Apex"] = 238,
                ["EntityState"] = 239,
                ["DrillCondition"] = 240,
                ["Index"] = 241,
                ["CelestialHash"] = 242,
                ["AlignmentError"] = 243,
                ["DistanceAu"] = 244,
                ["OrbitPeriod"] = 245,
                ["Inclination"] = 246,
                ["Eccentricity"] = 247,
                ["SemiMajorAxis"] = 248,
                ["DistanceKm"] = 249,
                ["CelestialParentHash"] = 250,
                ["TrueAnomaly"] = 251,
                ["RatioHydrogen"] = 252,
                ["RatioLiquidHydrogen"] = 253,
                ["RatioPollutedWater"] = 254,
                ["Discover"] = 255,
                ["Chart"] = 256,
                ["Survey"] = 257,
                ["NavPoints"] = 258,
                ["ChartedNavPoints"] = 259,
                ["Sites"] = 260,
                ["CurrentCode"] = 261,
                ["Density"] = 262,
                ["Richness"] = 263,
                ["Size"] = 264,
                ["TotalQuantity"] = 265,
                ["MinedQuantity"] = 266,
                ["BestContactFilter"] = 267,
                ["NameHash"] = 268,
                ["Altitude"] = 269,
                ["TargetSlotIndex"] = 270,
                ["TargetPrefabHash"] = 271,
                ["Extended"] = 272,
                ["NetworkFault"] = 273,
                ["ProportionalGain"] = 274,
                ["IntegralGain"] = 275,
                ["DerivativeGain"] = 276,
                ["Minimum"] = 277,
                ["Setpoint"] = 278,
                ["Reset"] = 279,
                ["StackSize"] = 280,
                ["NextWeatherHash"] = 281,
                ["ContactSlotIndex"] = 282,
                ["RatioHydrazine"] = 283,
                ["RatioLiquidHydrazine"] = 284,
                ["RatioLiquidAlcohol"] = 285,
                ["RatioHelium"] = 286,
                ["RatioLiquidSodiumChloride"] = 287,
                ["RatioSilanol"] = 288,
                ["RatioLiquidSilanol"] = 289,
                ["RatioHydrochloricAcid"] = 290,
                ["RatioLiquidHydrochloricAcid"] = 291,
                ["RatioOzone"] = 292,
                ["RatioLiquidOzone"] = 293,
                ["RatioHydrogenInput"] = 294,
                ["RatioHydrogenInput2"] = 295,
                ["RatioHydrogenOutput"] = 296,
                ["RatioHydrogenOutput2"] = 297,
                ["RatioLiquidHydrogenInput"] = 298,
                ["RatioLiquidHydrogenInput2"] = 299,
                ["RatioLiquidHydrogenOutput"] = 300,
                ["RatioLiquidHydrogenOutput2"] = 301,
                ["RatioPollutedWaterInput"] = 302,
                ["RatioPollutedWaterInput2"] = 303,
                ["RatioPollutedWaterOutput"] = 304,
                ["RatioPollutedWaterOutput2"] = 305,
                ["RatioHydrazineInput"] = 306,
                ["RatioHydrazineInput2"] = 307,
                ["RatioHydrazineOutput"] = 308,
                ["RatioHydrazineOutput2"] = 309,
                ["RatioLiquidHydrazineInput"] = 310,
                ["RatioLiquidHydrazineInput2"] = 311,
                ["RatioLiquidHydrazineOutput"] = 312,
                ["RatioLiquidHydrazineOutput2"] = 313,
                ["RatioLiquidAlcoholInput"] = 314,
                ["RatioLiquidAlcoholInput2"] = 315,
                ["RatioLiquidAlcoholOutput"] = 316,
                ["RatioLiquidAlcoholOutput2"] = 317,
                ["RatioHeliumInput"] = 318,
                ["RatioHeliumInput2"] = 319,
                ["RatioHeliumOutput"] = 320,
                ["RatioHeliumOutput2"] = 321,
                ["RatioLiquidSodiumChlorideInput"] = 322,
                ["RatioLiquidSodiumChlorideInput2"] = 323,
                ["RatioLiquidSodiumChlorideOutput"] = 324,
                ["RatioLiquidSodiumChlorideOutput2"] = 325,
                ["RatioSilanolInput"] = 326,
                ["RatioSilanolInput2"] = 327,
                ["RatioSilanolOutput"] = 328,
                ["RatioSilanolOutput2"] = 329,
                ["RatioLiquidSilanolInput"] = 330,
                ["RatioLiquidSilanolInput2"] = 331,
                ["RatioLiquidSilanolOutput"] = 332,
                ["RatioLiquidSilanolOutput2"] = 333,
                ["RatioHydrochloricAcidInput"] = 334,
                ["RatioHydrochloricAcidInput2"] = 335,
                ["RatioHydrochloricAcidOutput"] = 336,
                ["RatioHydrochloricAcidOutput2"] = 337,
                ["RatioLiquidHydrochloricAcidInput"] = 338,
                ["RatioLiquidHydrochloricAcidInput2"] = 339,
                ["RatioLiquidHydrochloricAcidOutput"] = 340,
                ["RatioLiquidHydrochloricAcidOutput2"] = 341,
                ["RatioOzoneInput"] = 342,
                ["RatioOzoneInput2"] = 343,
                ["RatioOzoneOutput"] = 344,
                ["RatioOzoneOutput2"] = 345,
                ["RatioLiquidOzoneInput"] = 346,
                ["RatioLiquidOzoneInput2"] = 347,
                ["RatioLiquidOzoneOutput"] = 348,
                ["RatioLiquidOzoneOutput2"] = 349,
                ["HealthDamage"] = 350,
                ["StunDamage"] = 351,
                ["CurrentNodeType"] = 352,
                ["TargetNodeType"] = 353,
                ["EnergyConvected"] = 354,
                ["EnergyRadiated"] = 355,
                ["Dispense"] = 356,
                ["DispenseSlot"] = 357,
                ["Gravity"] = 358,
            };

        public static IReadOnlyDictionary<string, int> LogicTypeByName => _LogicTypeByName;

        private static readonly Dictionary<string, int> _LogicSlotTypeByName =
            new Dictionary<string, int>(33, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Occupied"] = 1,
                ["OccupantHash"] = 2,
                ["Quantity"] = 3,
                ["Damage"] = 4,
                ["Efficiency"] = 5,
                ["Health"] = 6,
                ["Growth"] = 7,
                ["Pressure"] = 8,
                ["Temperature"] = 9,
                ["Charge"] = 10,
                ["ChargeRatio"] = 11,
                ["Class"] = 12,
                ["PressureWaste"] = 13,
                ["PressureAir"] = 14,
                ["MaxQuantity"] = 15,
                ["Mature"] = 16,
                ["PrefabHash"] = 17,
                ["Seeding"] = 18,
                ["LineNumber"] = 19,
                ["Volume"] = 20,
                ["Open"] = 21,
                ["On"] = 22,
                ["Lock"] = 23,
                ["SortingClass"] = 24,
                ["FilterType"] = 25,
                ["ReferenceId"] = 26,
                ["HarvestedHash"] = 27,
                ["Mode"] = 28,
                ["MaturityRatio"] = 29,
                ["SeedingRatio"] = 30,
                ["FreeSlots"] = 31,
                ["TotalSlots"] = 32,
            };

        public static IReadOnlyDictionary<string, int> LogicSlotTypeByName => _LogicSlotTypeByName;

        private static readonly Dictionary<string, int> _LogicReagentMode =
            new Dictionary<string, int>(4, StringComparer.Ordinal)
            {
                ["Contents"] = 0,
                ["Required"] = 1,
                ["Recipe"] = 2,
                ["TotalContents"] = 3,
            };

        public static IReadOnlyDictionary<string, int> LogicReagentMode => _LogicReagentMode;

        private static readonly Dictionary<string, int> _LogicBatchMethod =
            new Dictionary<string, int>(5, StringComparer.Ordinal)
            {
                ["Average"] = 0,
                ["Sum"] = 1,
                ["Minimum"] = 2,
                ["Maximum"] = 3,
                ["Count"] = 4,
            };

        public static IReadOnlyDictionary<string, int> LogicBatchMethod => _LogicBatchMethod;

        private static readonly Dictionary<string, int> _Sound =
            new Dictionary<string, int>(46, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Alarm2"] = 1,
                ["Alarm3"] = 2,
                ["Alarm4"] = 3,
                ["Alarm5"] = 4,
                ["Alarm6"] = 5,
                ["Alarm7"] = 6,
                ["Music1"] = 7,
                ["Music2"] = 8,
                ["Music3"] = 9,
                ["Alarm8"] = 10,
                ["Alarm9"] = 11,
                ["Alarm10"] = 12,
                ["Alarm11"] = 13,
                ["Alarm12"] = 14,
                ["Danger"] = 15,
                ["Warning"] = 16,
                ["Alert"] = 17,
                ["StormIncoming"] = 18,
                ["IntruderAlert"] = 19,
                ["Depressurising"] = 20,
                ["Pressurising"] = 21,
                ["AirlockCycling"] = 22,
                ["PowerLow"] = 23,
                ["SystemFailure"] = 24,
                ["Welcome"] = 25,
                ["MalfunctionDetected"] = 26,
                ["HaltWhoGoesThere"] = 27,
                ["FireFireFire"] = 28,
                ["One"] = 29,
                ["Two"] = 30,
                ["Three"] = 31,
                ["Four"] = 32,
                ["Five"] = 33,
                ["Floor"] = 34,
                ["RocketLaunching"] = 35,
                ["LiftOff"] = 36,
                ["TraderIncoming"] = 37,
                ["TraderLanded"] = 38,
                ["PressureHigh"] = 39,
                ["PressureLow"] = 40,
                ["TemperatureHigh"] = 41,
                ["TemperatureLow"] = 42,
                ["PollutantsDetected"] = 43,
                ["HighCarbonDioxide"] = 44,
                ["Alarm1"] = 45,
            };

        public static IReadOnlyDictionary<string, int> Sound => _Sound;

        private static readonly Dictionary<string, int> _TransmitterMode =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Passive"] = 0,
                ["Active"] = 1,
            };

        public static IReadOnlyDictionary<string, int> TransmitterMode => _TransmitterMode;

        private static readonly Dictionary<string, int> _ElevatorMode =
            new Dictionary<string, int>(3, StringComparer.Ordinal)
            {
                ["Stationary"] = 0,
                ["Upward"] = 1,
                ["Downward"] = 2,
            };

        public static IReadOnlyDictionary<string, int> ElevatorMode => _ElevatorMode;

        private static readonly Dictionary<string, int> _Color =
            new Dictionary<string, int>(12, StringComparer.Ordinal)
            {
                ["Blue"] = 0,
                ["Gray"] = 1,
                ["Green"] = 2,
                ["Orange"] = 3,
                ["Red"] = 4,
                ["Yellow"] = 5,
                ["White"] = 6,
                ["Black"] = 7,
                ["Brown"] = 8,
                ["Khaki"] = 9,
                ["Pink"] = 10,
                ["Purple"] = 11,
            };

        public static IReadOnlyDictionary<string, int> Color => _Color;

        private static readonly Dictionary<string, int> _EntityState =
            new Dictionary<string, int>(4, StringComparer.Ordinal)
            {
                ["Alive"] = 0,
                ["Dead"] = 1,
                ["Unconscious"] = 2,
                ["Decay"] = 3,
            };

        public static IReadOnlyDictionary<string, int> EntityState => _EntityState;

        private static readonly Dictionary<string, int> _AirControl =
            new Dictionary<string, int>(4, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Offline"] = 1,
                ["Pressure"] = 2,
                ["Draught"] = 4,
            };

        public static IReadOnlyDictionary<string, int> AirControl => _AirControl;

        private static readonly Dictionary<string, int> _DaylightSensorMode =
            new Dictionary<string, int>(3, StringComparer.Ordinal)
            {
                ["Default"] = 0,
                ["Horizontal"] = 1,
                ["Vertical"] = 2,
            };

        public static IReadOnlyDictionary<string, int> DaylightSensorMode => _DaylightSensorMode;

        private static readonly Dictionary<string, int> _ConditionOperation =
            new Dictionary<string, int>(4, StringComparer.Ordinal)
            {
                ["Equals"] = 0,
                ["Greater"] = 1,
                ["Less"] = 2,
                ["NotEquals"] = 3,
            };

        public static IReadOnlyDictionary<string, int> ConditionOperation => _ConditionOperation;

        private static readonly Dictionary<string, int> _AirCon =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Cold"] = 0,
                ["Hot"] = 1,
            };

        public static IReadOnlyDictionary<string, int> AirCon => _AirCon;

        private static readonly Dictionary<string, int> _Vent =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Inward"] = 1,
                ["Outward"] = 0,
            };

        public static IReadOnlyDictionary<string, int> Vent => _Vent;

        private static readonly Dictionary<string, int> _FiltrationMode =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Idle"] = 0,
                ["Active"] = 1,
            };

        public static IReadOnlyDictionary<string, int> FiltrationMode => _FiltrationMode;

        private static readonly Dictionary<string, int> _PowerMode =
            new Dictionary<string, int>(5, StringComparer.Ordinal)
            {
                ["Idle"] = 0,
                ["Charged"] = 4,
                ["Charging"] = 3,
                ["Discharging"] = 2,
                ["Discharged"] = 1,
            };

        public static IReadOnlyDictionary<string, int> PowerMode => _PowerMode;

        private static readonly Dictionary<string, int> _RobotMode =
            new Dictionary<string, int>(7, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["StorageFull"] = 6,
                ["Follow"] = 1,
                ["MoveToTarget"] = 2,
                ["PathToTarget"] = 5,
                ["Roam"] = 3,
                ["Unload"] = 4,
            };

        public static IReadOnlyDictionary<string, int> RobotMode => _RobotMode;

        private static readonly Dictionary<string, int> _SortingClass =
            new Dictionary<string, int>(11, StringComparer.Ordinal)
            {
                ["Default"] = 0,
                ["Kits"] = 1,
                ["Tools"] = 2,
                ["Resources"] = 3,
                ["Food"] = 4,
                ["Clothing"] = 5,
                ["Appliances"] = 6,
                ["Atmospherics"] = 7,
                ["Storage"] = 8,
                ["Ores"] = 9,
                ["Ices"] = 10,
            };

        public static IReadOnlyDictionary<string, int> SortingClass => _SortingClass;

        private static readonly Dictionary<string, int> _SlotClass =
            new Dictionary<string, int>(44, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Helmet"] = 1,
                ["Suit"] = 2,
                ["Back"] = 3,
                ["GasFilter"] = 4,
                ["GasCanister"] = 5,
                ["Motherboard"] = 6,
                ["Circuitboard"] = 7,
                ["DataDisk"] = 8,
                ["Organ"] = 9,
                ["Ore"] = 10,
                ["Plant"] = 11,
                ["Uniform"] = 12,
                ["Entity"] = 13,
                ["Battery"] = 14,
                ["Egg"] = 15,
                ["Belt"] = 16,
                ["Tool"] = 17,
                ["Appliance"] = 18,
                ["Ingot"] = 19,
                ["Torpedo"] = 20,
                ["Cartridge"] = 21,
                ["AccessCard"] = 22,
                ["Magazine"] = 23,
                ["Circuit"] = 24,
                ["Bottle"] = 25,
                ["ProgrammableChip"] = 26,
                ["Glasses"] = 27,
                ["CreditCard"] = 28,
                ["DirtCanister"] = 29,
                ["SensorProcessingUnit"] = 30,
                ["LiquidCanister"] = 31,
                ["LiquidBottle"] = 32,
                ["Wreckage"] = 33,
                ["SoundCartridge"] = 34,
                ["DrillHead"] = 35,
                ["ScanningHead"] = 36,
                ["Flare"] = 37,
                ["Blocked"] = 38,
                ["SuitMod"] = 39,
                ["Crate"] = 40,
                ["Portables"] = 41,
                ["RocketPayload"] = 42,
                ["AutoInjector"] = 43,
            };

        public static IReadOnlyDictionary<string, int> SlotClass => _SlotClass;

        private static readonly Dictionary<string, int> _GasType =
            new Dictionary<string, int>(31, StringComparer.Ordinal)
            {
                ["Undefined"] = 0,
                ["Oxygen"] = 1,
                ["Nitrogen"] = 2,
                ["CarbonDioxide"] = 4,
                ["Methane"] = 8,
                ["Pollutant"] = 16,
                ["Water"] = 32,
                ["NitrousOxide"] = 64,
                ["LiquidNitrogen"] = 128,
                ["LiquidOxygen"] = 256,
                ["LiquidMethane"] = 512,
                ["Steam"] = 1024,
                ["LiquidCarbonDioxide"] = 2048,
                ["LiquidPollutant"] = 4096,
                ["LiquidNitrousOxide"] = 8192,
                ["Hydrogen"] = 16384,
                ["LiquidHydrogen"] = 32768,
                ["PollutedWater"] = 65536,
                ["Hydrazine"] = 131072,
                ["LiquidHydrazine"] = 262144,
                ["LiquidAlcohol"] = 524288,
                ["Helium"] = 1048576,
                ["LiquidSodiumChloride"] = 2097152,
                ["Silanol"] = 4194304,
                ["LiquidSilanol"] = 8388608,
                ["HydrochloricAcid"] = 16777216,
                ["LiquidHydrochloricAcid"] = 33554432,
                ["Ozone"] = 67108864,
                ["LiquidOzone"] = 134217728,
                ["Air"] = 3,
                ["Fuel"] = 9,
            };

        public static IReadOnlyDictionary<string, int> GasType => _GasType;

        private static readonly Dictionary<string, int> _RocketMode =
            new Dictionary<string, int>(9, StringComparer.Ordinal)
            {
                ["Invalid"] = 0,
                ["None"] = 1,
                ["Mine"] = 2,
                ["Survey"] = 3,
                ["Discover"] = 4,
                ["Chart"] = 5,
                ["Deploy"] = 6,
                ["SurfaceScan"] = 7,
                ["Transfer"] = 8,
            };

        public static IReadOnlyDictionary<string, int> RocketMode => _RocketMode;

        private static readonly Dictionary<string, int> _ReEntryProfile =
            new Dictionary<string, int>(5, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Low"] = 1,
                ["Medium"] = 2,
                ["High"] = 3,
                ["Max"] = 4,
            };

        public static IReadOnlyDictionary<string, int> ReEntryProfile => _ReEntryProfile;

        private static readonly Dictionary<string, int> _SorterInstruction =
            new Dictionary<string, int>(7, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["FilterPrefabHashEquals"] = 1,
                ["FilterPrefabHashNotEquals"] = 2,
                ["FilterSortingClassCompare"] = 3,
                ["FilterSlotTypeCompare"] = 4,
                ["FilterQuantityCompare"] = 5,
                ["LimitNextExecutionByCount"] = 6,
            };

        public static IReadOnlyDictionary<string, int> SorterInstruction => _SorterInstruction;

        private static readonly Dictionary<string, int> _PrinterInstruction =
            new Dictionary<string, int>(10, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["StackPointer"] = 1,
                ["ExecuteRecipe"] = 2,
                ["WaitUntilNextValid"] = 3,
                ["JumpIfNextInvalid"] = 4,
                ["JumpToAddress"] = 5,
                ["DeviceSetLock"] = 6,
                ["EjectReagent"] = 7,
                ["EjectAllReagents"] = 8,
                ["MissingRecipeReagent"] = 9,
            };

        public static IReadOnlyDictionary<string, int> PrinterInstruction => _PrinterInstruction;

        private static readonly Dictionary<string, int> _TraderInstruction =
            new Dictionary<string, int>(19, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["WriteTraderData"] = 1,
                ["StrongestContactIdHash"] = 2,
                ["StrongestContactMetaData"] = 3,
                ["StrongestContactSignalData"] = 4,
                ["WriteTraderBuyData"] = 5,
                ["WriteTraderSellData"] = 6,
                ["TraderBuyThingData"] = 7,
                ["TraderBuyThingChildData"] = 8,
                ["TraderBuyGasData"] = 9,
                ["TraderSellThingData"] = 10,
                ["TraderSellGasData"] = 11,
                ["TraderSellThingChildData"] = 12,
                ["FilterPrefabHashEquals"] = 13,
                ["FilterPrefabHashNotEquals"] = 14,
                ["FilterSortingClassCompare"] = 15,
                ["FilterQuantityCompare"] = 16,
                ["FilterGasContains"] = 17,
                ["FilterGasNotContains"] = 18,
            };

        public static IReadOnlyDictionary<string, int> TraderInstruction => _TraderInstruction;

        private static readonly Dictionary<string, int> _ShuttleType =
            new Dictionary<string, int>(9, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Small"] = 1,
                ["SmallGas"] = 2,
                ["Medium"] = 3,
                ["MediumGas"] = 4,
                ["Large"] = 5,
                ["LargeGas"] = 6,
                ["MediumPlane"] = 7,
                ["LargePlane"] = 8,
            };

        public static IReadOnlyDictionary<string, int> ShuttleType => _ShuttleType;

        private static readonly Dictionary<string, int> _HashType =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Prefab"] = 0,
                ["GasLiquid"] = 1,
            };

        public static IReadOnlyDictionary<string, int> HashType => _HashType;

        private static readonly Dictionary<string, int> _DisplayMode =
            new Dictionary<string, int>(17, StringComparer.Ordinal)
            {
                ["Default"] = 0,
                ["Percent"] = 1,
                ["Power"] = 2,
                ["Kelvin"] = 3,
                ["Celsius"] = 4,
                ["Meters"] = 5,
                ["Credits"] = 6,
                ["Seconds"] = 7,
                ["Minutes"] = 8,
                ["Days"] = 9,
                ["String"] = 10,
                ["Fahrenheit"] = 11,
                ["Litres"] = 12,
                ["Mol"] = 13,
                ["Pa"] = 14,
                ["Newtons"] = 15,
                ["Degrees"] = 16,
            };

        public static IReadOnlyDictionary<string, int> DisplayMode => _DisplayMode;

        private static readonly Dictionary<string, int> _SettingDisplayMode =
            new Dictionary<string, int>(2, StringComparer.Ordinal)
            {
                ["Number"] = 0,
                ["String"] = 1,
            };

        public static IReadOnlyDictionary<string, int> SettingDisplayMode => _SettingDisplayMode;

        private static readonly Dictionary<string, int> _NodeType =
            new Dictionary<string, int>(7, StringComparer.Ordinal)
            {
                ["None"] = 0,
                ["Entry"] = 1,
                ["Static"] = 2,
                ["Generated"] = 3,
                ["LaunchPad"] = 4,
                ["LowOrbitHub"] = 5,
                ["LowOrbitLaunchPad"] = 6,
            };

        public static IReadOnlyDictionary<string, int> NodeType => _NodeType;

        private static readonly Dictionary<string, IReadOnlyDictionary<string, int>> _ConstantGroups =
            new Dictionary<string, IReadOnlyDictionary<string, int>>(30, StringComparer.Ordinal)
            {
                ["LogicType"] = _LogicTypeByName,
                ["LogicSlotType"] = _LogicSlotTypeByName,
                ["LogicReagentMode"] = _LogicReagentMode,
                ["LogicBatchMethod"] = _LogicBatchMethod,
                ["Sound"] = _Sound,
                ["TransmitterMode"] = _TransmitterMode,
                ["ElevatorMode"] = _ElevatorMode,
                ["Color"] = _Color,
                ["EntityState"] = _EntityState,
                ["AirControl"] = _AirControl,
                ["DaylightSensorMode"] = _DaylightSensorMode,
                ["ConditionOperation"] = _ConditionOperation,
                ["AirCon"] = _AirCon,
                ["Vent"] = _Vent,
                ["FiltrationMode"] = _FiltrationMode,
                ["PowerMode"] = _PowerMode,
                ["RobotMode"] = _RobotMode,
                ["SortingClass"] = _SortingClass,
                ["SlotClass"] = _SlotClass,
                ["GasType"] = _GasType,
                ["RocketMode"] = _RocketMode,
                ["ReEntryProfile"] = _ReEntryProfile,
                ["SorterInstruction"] = _SorterInstruction,
                ["PrinterInstruction"] = _PrinterInstruction,
                ["TraderInstruction"] = _TraderInstruction,
                ["ShuttleType"] = _ShuttleType,
                ["HashType"] = _HashType,
                ["DisplayMode"] = _DisplayMode,
                ["SettingDisplayMode"] = _SettingDisplayMode,
                ["NodeType"] = _NodeType,
            };

        /// <summary>Every named constant group the game exposes: Color, AirCon, GasType...</summary>
        public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> ConstantGroups => _ConstantGroups;
    }
}
